name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: beadando
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432 -U user; do
            echo "Waiting for postgres..."
            sleep 2
          done

      - name: Maven verify
        run: mvn verify
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/beadando
          SPRING_DATASOURCE_USERNAME: user
          SPRING_DATASOURCE_PASSWORD: password

      - name: Build with Maven
        run: mvn package
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/beadando
          SPRING_DATASOURCE_USERNAME: user
          SPRING_DATASOURCE_PASSWORD: password

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: beadando-artifact
          path: target/*.jar
